// Stedly Protocol — Brand Directory
//
// Bundled list of ~500 well-known brands across 14 categories. Used by
// trust.jsx for impersonation detection (display name says "Adobe" but
// email is on randomdomain.com), and by categorizer.js to mark senders
// as "verified brand" when they come from one of the legitimate domains.
//
// Schema:
//   key   = lowercase searchable name (matches against display names + body text)
//   value = { domains: [string], category: string, alias?: string }
//
// Coverage targets:
//   tech / saas: ~110 entries
//   retail / e-commerce: ~90
//   finance / banking: ~80
//   crypto: ~30
//   logistics: ~25
//   social: ~20
//   telecom: ~25
//   government: ~25
//   streaming: ~25
//   hosting / domains: ~25
//   pharma / health: ~25
//   travel / hospitality: ~20
//   airlines: ~20
//   influencer / lifestyle / DTC: ~30
//   stock tickers: covered via finance category for the most-impersonated
//
// When adding entries, prefer:
//   - the canonical apex domain
//   - any heavily-used regional variants (.co.uk, .de, etc.)
//   - any "transactional sender" subdomain that's stable (e.g. mail.stripe.com)
//
// Legitimate providers don't always send from the apex; we match endsWith
// in detectDisplayNameSpoof, so listing the apex covers all subdomains.

(function () {

  const BRAND_DIRECTORY = {
    // ─── Tech / SaaS ────────────────────────────────────────────────────
    google:        { domains: ["google.com","gmail.com","googlemail.com","youtube.com"], category: "tech" },
    microsoft:     { domains: ["microsoft.com","office.com","outlook.com","live.com","msn.com","hotmail.com","skype.com","xbox.com"], category: "tech" },
    apple:         { domains: ["apple.com","icloud.com","me.com","mac.com"], category: "tech" },
    adobe:         { domains: ["adobe.com","adobesc.com","adobe.io"], category: "tech" },
    notion:        { domains: ["notion.so","notion.com","makenotion.com"], category: "tech" },
    slack:         { domains: ["slack.com","slackhq.com"], category: "tech" },
    zoom:          { domains: ["zoom.us","zoomgov.com"], category: "tech" },
    dropbox:       { domains: ["dropbox.com","dropboxmail.com"], category: "tech" },
    github:        { domains: ["github.com","github.io"], category: "tech" },
    gitlab:        { domains: ["gitlab.com"], category: "tech" },
    bitbucket:     { domains: ["bitbucket.org","atlassian.com"], category: "tech" },
    atlassian:     { domains: ["atlassian.com","atlassian.net","jira.com","confluence.com","trello.com"], category: "tech" },
    jira:          { domains: ["atlassian.com","atlassian.net"], category: "tech" },
    trello:        { domains: ["trello.com","atlassian.com"], category: "tech" },
    asana:         { domains: ["asana.com"], category: "tech" },
    monday:        { domains: ["monday.com"], category: "tech" },
    clickup:       { domains: ["clickup.com"], category: "tech" },
    linear:        { domains: ["linear.app"], category: "tech" },
    salesforce:    { domains: ["salesforce.com","force.com","lightning.com"], category: "tech" },
    hubspot:       { domains: ["hubspot.com","hsforms.com","hsforms.net"], category: "tech" },
    zoho:          { domains: ["zoho.com","zoho.eu","zohomail.com"], category: "tech" },
    intercom:      { domains: ["intercom.com","intercom.io"], category: "tech" },
    figma:         { domains: ["figma.com"], category: "tech" },
    sketch:        { domains: ["sketch.com"], category: "tech" },
    canva:         { domains: ["canva.com"], category: "tech" },
    miro:          { domains: ["miro.com","mural.co"], category: "tech" },
    loom:          { domains: ["loom.com"], category: "tech" },
    calendly:      { domains: ["calendly.com"], category: "tech" },
    typeform:      { domains: ["typeform.com"], category: "tech" },
    docusign:      { domains: ["docusign.com","docusign.net"], category: "tech" },
    hellosign:     { domains: ["hellosign.com","dropbox.com"], category: "tech" },
    pandadoc:      { domains: ["pandadoc.com"], category: "tech" },
    grammarly:     { domains: ["grammarly.com"], category: "tech" },
    superhuman:    { domains: ["superhuman.com"], category: "tech" },
    fastmail:      { domains: ["fastmail.com","fastmail.fm"], category: "tech" },
    protonmail:    { domains: ["protonmail.com","proton.me","pm.me"], category: "tech" },
    aws:           { domains: ["aws.amazon.com","amazonaws.com","amazon.com"], category: "tech" },
    azure:         { domains: ["microsoft.com","azure.com"], category: "tech" },
    gcp:           { domains: ["cloud.google.com","google.com"], category: "tech" },
    digitalocean:  { domains: ["digitalocean.com"], category: "tech" },
    cloudflare:    { domains: ["cloudflare.com"], category: "tech" },
    vercel:        { domains: ["vercel.com"], category: "tech" },
    netlify:       { domains: ["netlify.com"], category: "tech" },
    heroku:        { domains: ["heroku.com","salesforce.com"], category: "tech" },
    twilio:        { domains: ["twilio.com","sendgrid.com","sendgrid.net"], category: "tech" },
    sendgrid:      { domains: ["sendgrid.com","sendgrid.net"], category: "tech" },
    mailgun:       { domains: ["mailgun.com","mailgun.net"], category: "tech" },
    mailchimp:     { domains: ["mailchimp.com","mailchimpapp.com"], category: "tech" },
    klaviyo:       { domains: ["klaviyo.com"], category: "tech" },
    constantcontact: { domains: ["constantcontact.com"], category: "tech" },
    shopify:       { domains: ["shopify.com","myshopify.com"], category: "tech" },
    bigcommerce:   { domains: ["bigcommerce.com"], category: "tech" },
    woocommerce:   { domains: ["woocommerce.com","automattic.com"], category: "tech" },
    squarespace:   { domains: ["squarespace.com"], category: "tech" },
    wix:           { domains: ["wix.com"], category: "tech" },
    webflow:       { domains: ["webflow.com"], category: "tech" },
    wordpress:     { domains: ["wordpress.com","wordpress.org","automattic.com"], category: "tech" },
    automattic:    { domains: ["automattic.com","wordpress.com"], category: "tech" },
    quickbooks:    { domains: ["quickbooks.com","intuit.com"], category: "tech" },
    intuit:        { domains: ["intuit.com","quickbooks.com","turbotax.com","mint.com","creditkarma.com"], category: "tech" },
    turbotax:      { domains: ["turbotax.com","intuit.com"], category: "tech" },
    xero:          { domains: ["xero.com"], category: "tech" },
    workday:       { domains: ["workday.com"], category: "tech" },
    oracle:        { domains: ["oracle.com"], category: "tech" },
    sap:           { domains: ["sap.com"], category: "tech" },
    ibm:           { domains: ["ibm.com"], category: "tech" },
    cisco:         { domains: ["cisco.com","webex.com"], category: "tech" },
    samsung:       { domains: ["samsung.com"], category: "tech" },
    intel:         { domains: ["intel.com"], category: "tech" },
    nvidia:        { domains: ["nvidia.com"], category: "tech" },
    amd:           { domains: ["amd.com"], category: "tech" },
    dell:          { domains: ["dell.com"], category: "tech" },
    hp:            { domains: ["hp.com"], category: "tech" },
    lenovo:        { domains: ["lenovo.com"], category: "tech" },
    "chatgpt":     { domains: ["openai.com","chatgpt.com"], category: "tech" },
    openai:        { domains: ["openai.com","chatgpt.com"], category: "tech" },
    anthropic:     { domains: ["anthropic.com","claude.ai"], category: "tech" },
    perplexity:    { domains: ["perplexity.ai"], category: "tech" },
    midjourney:    { domains: ["midjourney.com"], category: "tech" },
    "1password":   { domains: ["1password.com"], category: "tech" },
    lastpass:      { domains: ["lastpass.com","logmeininc.com"], category: "tech" },
    bitwarden:     { domains: ["bitwarden.com"], category: "tech" },
    okta:          { domains: ["okta.com"], category: "tech" },
    auth0:         { domains: ["auth0.com","okta.com"], category: "tech" },
    duo:           { domains: ["duo.com","cisco.com"], category: "tech" },
    norton:        { domains: ["norton.com","nortonlifelock.com"], category: "tech" },
    mcafee:        { domains: ["mcafee.com"], category: "tech" },
    kaspersky:     { domains: ["kaspersky.com"], category: "tech" },
    malwarebytes:  { domains: ["malwarebytes.com"], category: "tech" },

    // ─── Retail / E-commerce ────────────────────────────────────────────
    amazon:        { domains: ["amazon.com","amazon.co.uk","amazon.ca","amazon.de","amazon.fr","amazon.es","amazon.it","amazon.in","amazon.com.au","amazon.co.jp","amazon.com.br","amazon.com.mx","amazonaws.com"], category: "retail" },
    ebay:          { domains: ["ebay.com","ebay.co.uk","ebay.de","ebay.fr"], category: "retail" },
    walmart:       { domains: ["walmart.com"], category: "retail" },
    target:        { domains: ["target.com"], category: "retail" },
    bestbuy:       { domains: ["bestbuy.com"], category: "retail" },
    "best buy":    { domains: ["bestbuy.com"], category: "retail" },
    costco:        { domains: ["costco.com"], category: "retail" },
    "sam's club":  { domains: ["samsclub.com"], category: "retail" },
    macys:         { domains: ["macys.com"], category: "retail" },
    nordstrom:     { domains: ["nordstrom.com","nordstromrack.com"], category: "retail" },
    kohls:         { domains: ["kohls.com"], category: "retail" },
    "home depot":  { domains: ["homedepot.com"], category: "retail" },
    "lowes":       { domains: ["lowes.com"], category: "retail" },
    sephora:       { domains: ["sephora.com"], category: "retail" },
    ulta:          { domains: ["ulta.com"], category: "retail" },
    wayfair:       { domains: ["wayfair.com"], category: "retail" },
    etsy:          { domains: ["etsy.com"], category: "retail" },
    aliexpress:    { domains: ["aliexpress.com","aliexpress.us"], category: "retail" },
    alibaba:       { domains: ["alibaba.com","aliexpress.com"], category: "retail" },
    rakuten:       { domains: ["rakuten.com","rakuten.co.jp"], category: "retail" },
    newegg:        { domains: ["newegg.com"], category: "retail" },
    overstock:     { domains: ["overstock.com","bedbathandbeyond.com"], category: "retail" },
    chewy:         { domains: ["chewy.com"], category: "retail" },
    petsmart:      { domains: ["petsmart.com"], category: "retail" },
    petco:         { domains: ["petco.com"], category: "retail" },
    instacart:     { domains: ["instacart.com"], category: "retail" },
    doordash:      { domains: ["doordash.com"], category: "retail" },
    ubereats:      { domains: ["ubereats.com","uber.com"], category: "retail" },
    grubhub:       { domains: ["grubhub.com"], category: "retail" },
    seamless:      { domains: ["seamless.com","grubhub.com"], category: "retail" },
    postmates:     { domains: ["postmates.com","uber.com"], category: "retail" },
    uber:          { domains: ["uber.com","ubereats.com"], category: "retail" },
    lyft:          { domains: ["lyft.com"], category: "retail" },
    airbnb:        { domains: ["airbnb.com","airbnb.co.uk"], category: "travel" },
    booking:       { domains: ["booking.com"], category: "travel" },
    "booking.com": { domains: ["booking.com"], category: "travel" },
    expedia:       { domains: ["expedia.com","hotels.com","vrbo.com","trivago.com"], category: "travel" },
    hotels:        { domains: ["hotels.com","expedia.com"], category: "travel" },
    "hotels.com":  { domains: ["hotels.com"], category: "travel" },
    vrbo:          { domains: ["vrbo.com","expedia.com"], category: "travel" },
    kayak:         { domains: ["kayak.com","booking.com"], category: "travel" },
    priceline:     { domains: ["priceline.com","booking.com"], category: "travel" },
    trivago:       { domains: ["trivago.com"], category: "travel" },
    tripadvisor:   { domains: ["tripadvisor.com"], category: "travel" },

    // ─── Finance / Banking ─────────────────────────────────────────────
    chase:                { domains: ["chase.com","jpmorgan.com","jpmorganchase.com"], category: "finance" },
    "wells fargo":        { domains: ["wellsfargo.com"], category: "finance" },
    wellsfargo:           { domains: ["wellsfargo.com"], category: "finance" },
    "bank of america":    { domains: ["bankofamerica.com","bofa.com"], category: "finance" },
    bankofamerica:        { domains: ["bankofamerica.com","bofa.com"], category: "finance" },
    citi:                 { domains: ["citi.com","citibank.com","citigroup.com"], category: "finance" },
    citibank:             { domains: ["citi.com","citibank.com"], category: "finance" },
    capitalone:           { domains: ["capitalone.com"], category: "finance" },
    "capital one":        { domains: ["capitalone.com"], category: "finance" },
    "us bank":            { domains: ["usbank.com"], category: "finance" },
    pnc:                  { domains: ["pnc.com"], category: "finance" },
    truist:               { domains: ["truist.com"], category: "finance" },
    "td bank":            { domains: ["td.com","tdbank.com"], category: "finance" },
    hsbc:                 { domains: ["hsbc.com","hsbc.co.uk","us.hsbc.com"], category: "finance" },
    barclays:             { domains: ["barclays.com","barclays.co.uk","barclaycardus.com"], category: "finance" },
    santander:            { domains: ["santander.com","santanderbank.com"], category: "finance" },
    "american express":   { domains: ["americanexpress.com","aexp.com"], category: "finance" },
    amex:                 { domains: ["americanexpress.com","aexp.com"], category: "finance" },
    discover:             { domains: ["discover.com"], category: "finance" },
    visa:                 { domains: ["visa.com"], category: "finance" },
    mastercard:           { domains: ["mastercard.com","mastercard.us"], category: "finance" },
    paypal:               { domains: ["paypal.com","paypal.co.uk","paypal.de","paypal.fr"], category: "finance" },
    venmo:                { domains: ["venmo.com","paypal.com"], category: "finance" },
    "cash app":           { domains: ["cash.app","squareup.com","block.xyz"], category: "finance" },
    cashapp:              { domains: ["cash.app","squareup.com"], category: "finance" },
    zelle:                { domains: ["zellepay.com"], category: "finance" },
    wise:                 { domains: ["wise.com","transferwise.com"], category: "finance" },
    revolut:              { domains: ["revolut.com"], category: "finance" },
    n26:                  { domains: ["n26.com"], category: "finance" },
    monzo:                { domains: ["monzo.com"], category: "finance" },
    chime:                { domains: ["chime.com"], category: "finance" },
    sofi:                 { domains: ["sofi.com"], category: "finance" },
    robinhood:            { domains: ["robinhood.com"], category: "finance" },
    schwab:               { domains: ["schwab.com","schwabplan.com"], category: "finance" },
    "charles schwab":     { domains: ["schwab.com"], category: "finance" },
    fidelity:             { domains: ["fidelity.com"], category: "finance" },
    vanguard:             { domains: ["vanguard.com"], category: "finance" },
    blackrock:            { domains: ["blackrock.com","ishares.com"], category: "finance" },
    "goldman sachs":      { domains: ["goldmansachs.com","gs.com","marcus.com"], category: "finance" },
    goldman:              { domains: ["goldmansachs.com","gs.com","marcus.com"], category: "finance" },
    jpmorgan:             { domains: ["jpmorgan.com","chase.com","jpmorganchase.com"], category: "finance" },
    "morgan stanley":     { domains: ["morganstanley.com","ms.com"], category: "finance" },
    etrade:               { domains: ["etrade.com","morganstanley.com"], category: "finance" },
    "e*trade":            { domains: ["etrade.com","morganstanley.com"], category: "finance" },
    interactivebrokers:   { domains: ["interactivebrokers.com"], category: "finance" },
    "interactive brokers":{ domains: ["interactivebrokers.com"], category: "finance" },
    plaid:                { domains: ["plaid.com"], category: "finance" },
    stripe:               { domains: ["stripe.com"], category: "finance" },
    square:               { domains: ["squareup.com","square.com","block.xyz"], category: "finance" },
    block:                { domains: ["block.xyz","squareup.com"], category: "finance" },
    affirm:               { domains: ["affirm.com"], category: "finance" },
    klarna:               { domains: ["klarna.com"], category: "finance" },
    afterpay:             { domains: ["afterpay.com","squareup.com"], category: "finance" },
    "credit karma":       { domains: ["creditkarma.com","intuit.com"], category: "finance" },

    // ─── Crypto ────────────────────────────────────────────────────────
    coinbase:    { domains: ["coinbase.com"], category: "crypto" },
    binance:     { domains: ["binance.com","binance.us"], category: "crypto" },
    kraken:      { domains: ["kraken.com"], category: "crypto" },
    gemini:      { domains: ["gemini.com"], category: "crypto" },
    bitfinex:    { domains: ["bitfinex.com"], category: "crypto" },
    kucoin:      { domains: ["kucoin.com"], category: "crypto" },
    "crypto.com":{ domains: ["crypto.com"], category: "crypto" },
    okx:         { domains: ["okx.com"], category: "crypto" },
    bybit:       { domains: ["bybit.com"], category: "crypto" },
    bitstamp:    { domains: ["bitstamp.net"], category: "crypto" },
    ledger:      { domains: ["ledger.com"], category: "crypto" },
    trezor:      { domains: ["trezor.io"], category: "crypto" },
    metamask:    { domains: ["metamask.io","consensys.net"], category: "crypto" },
    opensea:     { domains: ["opensea.io"], category: "crypto" },
    blockchain:  { domains: ["blockchain.com","blockchain.info"], category: "crypto" },

    // ─── Logistics / Shipping ──────────────────────────────────────────
    fedex:       { domains: ["fedex.com"], category: "logistics" },
    ups:         { domains: ["ups.com"], category: "logistics" },
    usps:        { domains: ["usps.com","usps.gov"], category: "logistics" },
    dhl:         { domains: ["dhl.com","dhlexpress.com"], category: "logistics" },
    "amazon logistics": { domains: ["amazon.com","amzl.com"], category: "logistics" },
    ontrac:      { domains: ["ontrac.com"], category: "logistics" },
    lasership:   { domains: ["lasership.com"], category: "logistics" },
    gls:         { domains: ["gls-group.eu","gls-group.com","gls-us.com"], category: "logistics" },
    royalmail:   { domains: ["royalmail.com"], category: "logistics" },
    "royal mail":{ domains: ["royalmail.com"], category: "logistics" },
    canadapost:  { domains: ["canadapost.ca","canadapost-postescanada.ca"], category: "logistics" },
    "canada post":{domains: ["canadapost.ca"], category: "logistics" },
    "australia post": { domains: ["auspost.com.au"], category: "logistics" },

    // ─── Social ────────────────────────────────────────────────────────
    facebook:    { domains: ["facebook.com","fb.com","meta.com","fbmail.com"], category: "social" },
    instagram:   { domains: ["instagram.com","mail.instagram.com","facebook.com","meta.com"], category: "social" },
    meta:        { domains: ["meta.com","facebook.com","fb.com"], category: "social" },
    twitter:     { domains: ["twitter.com","x.com"], category: "social" },
    x:           { domains: ["x.com","twitter.com"], category: "social" },
    linkedin:    { domains: ["linkedin.com"], category: "social" },
    tiktok:      { domains: ["tiktok.com","bytedance.com"], category: "social" },
    snapchat:    { domains: ["snapchat.com","snap.com"], category: "social" },
    whatsapp:    { domains: ["whatsapp.com","fb.com","meta.com"], category: "social" },
    telegram:    { domains: ["telegram.org"], category: "social" },
    discord:     { domains: ["discord.com","discord.gg","discordapp.com"], category: "social" },
    reddit:      { domains: ["reddit.com","redditmail.com"], category: "social" },
    pinterest:   { domains: ["pinterest.com"], category: "social" },
    tumblr:      { domains: ["tumblr.com","automattic.com"], category: "social" },
    quora:       { domains: ["quora.com"], category: "social" },
    medium:      { domains: ["medium.com"], category: "social" },
    substack:    { domains: ["substack.com"], category: "social" },
    twitch:      { domains: ["twitch.tv","amazon.com"], category: "social" },

    // ─── Telecom ───────────────────────────────────────────────────────
    "at&t":      { domains: ["att.com","attmail.com","sbcglobal.net"], category: "telecom" },
    att:         { domains: ["att.com","attmail.com"], category: "telecom" },
    verizon:     { domains: ["verizon.com","verizonwireless.com","verizon.net"], category: "telecom" },
    "t-mobile":  { domains: ["t-mobile.com","tmobile.com","sprint.com"], category: "telecom" },
    tmobile:     { domains: ["t-mobile.com","tmobile.com"], category: "telecom" },
    sprint:      { domains: ["sprint.com","t-mobile.com"], category: "telecom" },
    comcast:     { domains: ["comcast.com","xfinity.com"], category: "telecom" },
    xfinity:     { domains: ["xfinity.com","comcast.com"], category: "telecom" },
    spectrum:    { domains: ["spectrum.com","spectrum.net","charter.com"], category: "telecom" },
    cox:         { domains: ["cox.com","cox.net"], category: "telecom" },
    centurylink: { domains: ["centurylink.com","centurylink.net","lumen.com"], category: "telecom" },
    vodafone:    { domains: ["vodafone.com","vodafone.co.uk","vodafone.de"], category: "telecom" },
    o2:          { domains: ["o2.co.uk","o2online.de"], category: "telecom" },
    ee:          { domains: ["ee.co.uk","bt.com"], category: "telecom" },
    "british telecom": { domains: ["bt.com"], category: "telecom" },
    bt:          { domains: ["bt.com"], category: "telecom" },
    rogers:      { domains: ["rogers.com","fido.ca","chatr.ca"], category: "telecom" },
    bell:        { domains: ["bell.ca","bellsympatico.ca","sympatico.ca"], category: "telecom" },

    // ─── Government ────────────────────────────────────────────────────
    irs:         { domains: ["irs.gov"], category: "gov" },
    ssa:         { domains: ["ssa.gov","socialsecurity.gov"], category: "gov" },
    "social security": { domains: ["ssa.gov","socialsecurity.gov"], category: "gov" },
    dmv:         { domains: ["dmv.org","dmv.ca.gov","dmv.ny.gov","dmv.virginia.gov"], category: "gov" },
    fbi:         { domains: ["fbi.gov","ic3.gov"], category: "gov" },
    cia:         { domains: ["cia.gov"], category: "gov" },
    ftc:         { domains: ["ftc.gov","consumer.ftc.gov"], category: "gov" },
    fda:         { domains: ["fda.gov"], category: "gov" },
    epa:         { domains: ["epa.gov"], category: "gov" },
    sec:         { domains: ["sec.gov"], category: "gov" },
    cdc:         { domains: ["cdc.gov"], category: "gov" },
    nih:         { domains: ["nih.gov"], category: "gov" },
    medicare:    { domains: ["medicare.gov","cms.gov"], category: "gov" },
    medicaid:    { domains: ["medicaid.gov","cms.gov"], category: "gov" },
    "white house": { domains: ["whitehouse.gov"], category: "gov" },
    "us army":   { domains: ["army.mil"], category: "gov" },
    "us navy":   { domains: ["navy.mil"], category: "gov" },
    "us air force":{ domains: ["af.mil"], category: "gov" },
    "us marines":{ domains: ["marines.mil"], category: "gov" },
    "uk gov":    { domains: ["gov.uk"], category: "gov" },
    hmrc:        { domains: ["gov.uk","hmrc.gov.uk"], category: "gov" },

    // ─── Streaming / Entertainment ─────────────────────────────────────
    netflix:     { domains: ["netflix.com","mailer.netflix.com"], category: "streaming" },
    hulu:        { domains: ["hulu.com","disney.com"], category: "streaming" },
    "disney+":   { domains: ["disneyplus.com","disney.com"], category: "streaming" },
    disneyplus:  { domains: ["disneyplus.com","disney.com"], category: "streaming" },
    disney:      { domains: ["disney.com","disneyplus.com","hulu.com","espn.com"], category: "streaming" },
    "hbo max":   { domains: ["max.com","hbomax.com","hbo.com","wbd.com"], category: "streaming" },
    max:         { domains: ["max.com","hbomax.com","wbd.com"], category: "streaming" },
    spotify:     { domains: ["spotify.com"], category: "streaming" },
    "apple music":{domains: ["apple.com","applemusic.com","icloud.com"], category: "streaming" },
    "amazon music":{domains: ["amazon.com"], category: "streaming" },
    youtube:     { domains: ["youtube.com","google.com"], category: "streaming" },
    pandora:     { domains: ["pandora.com","siriusxm.com"], category: "streaming" },
    siriusxm:    { domains: ["siriusxm.com"], category: "streaming" },
    "paramount+":{ domains: ["paramountplus.com","paramount.com","cbs.com"], category: "streaming" },
    paramount:   { domains: ["paramountplus.com","paramount.com"], category: "streaming" },
    peacock:     { domains: ["peacocktv.com","nbcuni.com"], category: "streaming" },
    "apple tv":  { domains: ["apple.com","tv.apple.com"], category: "streaming" },
    crunchyroll: { domains: ["crunchyroll.com"], category: "streaming" },

    // ─── Hosting / Domains ─────────────────────────────────────────────
    godaddy:     { domains: ["godaddy.com","secureserver.net"], category: "hosting" },
    ionos:       { domains: ["ionos.com","ionos.de","1and1.com","1and1.net","1and1.es","1and1.co.uk"], category: "hosting" },
    "1&1":       { domains: ["1and1.com","ionos.com","ionos.de"], category: "hosting" },
    namecheap:   { domains: ["namecheap.com"], category: "hosting" },
    bluehost:    { domains: ["bluehost.com","newfold.com"], category: "hosting" },
    hostgator:   { domains: ["hostgator.com","newfold.com"], category: "hosting" },
    siteground:  { domains: ["siteground.com"], category: "hosting" },
    dreamhost:   { domains: ["dreamhost.com"], category: "hosting" },
    wpengine:    { domains: ["wpengine.com"], category: "hosting" },
    "wp engine": { domains: ["wpengine.com"], category: "hosting" },
    kinsta:      { domains: ["kinsta.com"], category: "hosting" },
    flywheel:    { domains: ["getflywheel.com"], category: "hosting" },
    googledomains:{domains: ["domains.google","google.com"], category: "hosting" },
    porkbun:     { domains: ["porkbun.com"], category: "hosting" },
    cloudflareregistrar:{domains: ["cloudflare.com"], category: "hosting" },

    // ─── Pharma / Health ───────────────────────────────────────────────
    cvs:         { domains: ["cvs.com","cvshealth.com"], category: "health" },
    walgreens:   { domains: ["walgreens.com"], category: "health" },
    riteaid:     { domains: ["riteaid.com"], category: "health" },
    "rite aid":  { domains: ["riteaid.com"], category: "health" },
    "express scripts":{domains: ["express-scripts.com"], category: "health" },
    optum:       { domains: ["optum.com","unitedhealthgroup.com"], category: "health" },
    unitedhealth:{ domains: ["unitedhealthcare.com","uhc.com","unitedhealthgroup.com"], category: "health" },
    "united healthcare":{domains: ["unitedhealthcare.com","uhc.com"], category: "health" },
    aetna:       { domains: ["aetna.com","cvshealth.com"], category: "health" },
    cigna:       { domains: ["cigna.com"], category: "health" },
    humana:      { domains: ["humana.com"], category: "health" },
    "blue cross":{ domains: ["bcbs.com","anthem.com"], category: "health" },
    bcbs:        { domains: ["bcbs.com","anthem.com"], category: "health" },
    anthem:      { domains: ["anthem.com","elevancehealth.com"], category: "health" },
    kaiser:      { domains: ["kp.org","kaiserpermanente.org"], category: "health" },
    "kaiser permanente":{domains: ["kp.org","kaiserpermanente.org"], category: "health" },
    pfizer:      { domains: ["pfizer.com"], category: "health" },
    moderna:     { domains: ["modernatx.com"], category: "health" },
    johnson:     { domains: ["jnj.com"], category: "health" },
    "johnson & johnson":{domains: ["jnj.com"], category: "health" },
    "j&j":       { domains: ["jnj.com"], category: "health" },
    merck:       { domains: ["merck.com","msd.com"], category: "health" },

    // ─── Airlines ──────────────────────────────────────────────────────
    united:           { domains: ["united.com"], category: "airline" },
    delta:            { domains: ["delta.com"], category: "airline" },
    american:         { domains: ["aa.com","americanairlines.com"], category: "airline" },
    "american airlines":{domains: ["aa.com","americanairlines.com"], category: "airline" },
    southwest:        { domains: ["southwest.com"], category: "airline" },
    jetblue:          { domains: ["jetblue.com"], category: "airline" },
    alaska:           { domains: ["alaskaair.com"], category: "airline" },
    spirit:           { domains: ["spirit.com"], category: "airline" },
    frontier:         { domains: ["flyfrontier.com"], category: "airline" },
    "british airways":{ domains: ["britishairways.com"], category: "airline" },
    lufthansa:        { domains: ["lufthansa.com"], category: "airline" },
    klm:              { domains: ["klm.com"], category: "airline" },
    "air france":     { domains: ["airfrance.com","airfranceklm.com"], category: "airline" },
    qatar:            { domains: ["qatarairways.com"], category: "airline" },
    emirates:         { domains: ["emirates.com"], category: "airline" },
    qantas:           { domains: ["qantas.com"], category: "airline" },
    "air canada":     { domains: ["aircanada.com"], category: "airline" },
    "ryan air":       { domains: ["ryanair.com"], category: "airline" },
    ryanair:          { domains: ["ryanair.com"], category: "airline" },
    "easyjet":        { domains: ["easyjet.com"], category: "airline" },

    // ─── Influencer / Lifestyle / DTC ──────────────────────────────────
    "g fuel":     { domains: ["gfuel.com"], category: "lifestyle" },
    gfuel:        { domains: ["gfuel.com"], category: "lifestyle" },
    gymshark:     { domains: ["gymshark.com"], category: "lifestyle" },
    lululemon:    { domains: ["lululemon.com"], category: "lifestyle" },
    nike:         { domains: ["nike.com"], category: "lifestyle" },
    adidas:       { domains: ["adidas.com"], category: "lifestyle" },
    "under armour":{ domains: ["underarmour.com"], category: "lifestyle" },
    underarmour:  { domains: ["underarmour.com"], category: "lifestyle" },
    patagonia:    { domains: ["patagonia.com"], category: "lifestyle" },
    "north face": { domains: ["thenorthface.com","vfc.com"], category: "lifestyle" },
    columbia:     { domains: ["columbia.com"], category: "lifestyle" },
    rei:          { domains: ["rei.com"], category: "lifestyle" },
    allbirds:     { domains: ["allbirds.com"], category: "lifestyle" },
    warbyparker:  { domains: ["warbyparker.com"], category: "lifestyle" },
    "warby parker":{domains: ["warbyparker.com"], category: "lifestyle" },
    casper:       { domains: ["casper.com"], category: "lifestyle" },
    purple:       { domains: ["purple.com"], category: "lifestyle" },
    glossier:     { domains: ["glossier.com"], category: "lifestyle" },
    fenty:        { domains: ["fentybeauty.com"], category: "lifestyle" },
    rare:         { domains: ["rarebeauty.com"], category: "lifestyle" },
    "rare beauty":{ domains: ["rarebeauty.com"], category: "lifestyle" },
    drunkelephant:{ domains: ["drunkelephant.com"], category: "lifestyle" },
    "drunk elephant":{domains: ["drunkelephant.com"], category: "lifestyle" },
    bambu:        { domains: ["drinkbambu.com"], category: "lifestyle" },
    liquidiv:     { domains: ["liquid-iv.com"], category: "lifestyle" },
    "liquid iv":  { domains: ["liquid-iv.com"], category: "lifestyle" },
    olipop:       { domains: ["drinkolipop.com"], category: "lifestyle" },
    poppi:        { domains: ["drinkpoppi.com"], category: "lifestyle" },
    "athletic greens": { domains: ["drinkag1.com","athleticgreens.com"], category: "lifestyle" },
    ag1:          { domains: ["drinkag1.com","athleticgreens.com"], category: "lifestyle" },
    huel:         { domains: ["huel.com"], category: "lifestyle" },
    soylent:      { domains: ["soylent.com"], category: "lifestyle" },
    blueapron:    { domains: ["blueapron.com"], category: "lifestyle" },
    "blue apron": { domains: ["blueapron.com"], category: "lifestyle" },
    hellofresh:   { domains: ["hellofresh.com"], category: "lifestyle" },
    "hello fresh":{ domains: ["hellofresh.com"], category: "lifestyle" },
    factor:       { domains: ["factor75.com","hellofresh.com"], category: "lifestyle" },
    starbucks:    { domains: ["starbucks.com"], category: "lifestyle" },
    chipotle:     { domains: ["chipotle.com"], category: "lifestyle" },
    mcdonalds:    { domains: ["mcdonalds.com"], category: "lifestyle" },
    "burger king":{ domains: ["bk.com","burgerking.com"], category: "lifestyle" },
    wendy:        { domains: ["wendys.com"], category: "lifestyle" },
    "panera":     { domains: ["panerabread.com"], category: "lifestyle" },
    "dominos":    { domains: ["dominos.com"], category: "lifestyle" },
    "pizza hut":  { domains: ["pizzahut.com"], category: "lifestyle" },
  };

  // Fast lookup helpers.
  function brandByDomain(domain) {
    if (!domain) return null;
    const d = domain.toLowerCase();
    for (const [name, entry] of Object.entries(BRAND_DIRECTORY)) {
      if (entry.domains.some((legit) => d === legit || d.endsWith("." + legit))) {
        return { name, ...entry };
      }
    }
    return null;
  }

  function brandList() {
    return Object.keys(BRAND_DIRECTORY);
  }

  Object.assign(window, { BRAND_DIRECTORY, brandByDomain, brandList });
})();
